name: Package plugin
description: Packages the plugin for specified architecture and build config.
inputs:
  target:
    description: Build target for dependencies
    required: true
  config:
    description: Build configuration
    required: false
    default: RelWithDebInfo
  package:
    description: Create Windows installation package
    required: false
    default: 'false'
runs:
  using: composite
  steps:
    - name: Run Windows Packaging
      shell: pwsh
      run: |
        # Run Windows Packaging
        if ( $Env:RUNNER_DEBUG -ne $null ) {
          Set-PSDebug -Trace 1
        }

        $PackageArgs = @{
          Target = '${{ inputs.target }}'
          Configuration = '${{ inputs.config }}'
        }

        .github/scripts/Package-Windows.ps1 @PackageArgs
